### PR TITLE
Solved - Find it Rename it!! #1

### PR DESCRIPTION
**Pull request by IshaanXCoder**
Solved issue #1 - Find it Rename it!!

Renamed mermoria.go to memoria.go.
Attached a screenshot for reference.
Screenshot 2024-12-17 at 2 50 25 PM

### CODE REVIEW

**Comment by IshaanXCoder** [comment]
Solved issue #1 , renamed the file

**Comment by utkarshdagoat** [comment]
Hey thanks for solving

**Comment by utkarshdagoat** [comment]
Hey thanks for solving but I cannot merge your pr as you are pushing two commits for future refrence please open pr with commits only for that pr

**Comment by utkarshdagoat** [comment]
I am closing this pr so you raise a new one

**Pull request closed without merging**
